server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/coubee-report
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update #create로 변경해도 됨
      generate-ddl: true
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

